### ISSUE TITLE
Error when login a new user

### ISSUE THREAD

**Issue by petruspierre** [wendelfreitas/animavita#79]
**STEPS TO REPRODUCE**:
- Run the app and graphql API
- Login with a new user

**EXPECTED BEHAVIOR**:
Create a new user in the database and login normally

**ACTUAL BEHAVIOR**:
User is created in database, but API return an error and print the following log:

```shell
Error: getaddrinfo EAI_AGAIN us-east-1
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  locations: [ { line: 4, column: 3 } ],
  path: [ 'SaveFacebookUser' ]
}
GraphQL Error {
  error: Error: getaddrinfo EAI_AGAIN us-east-1
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    locations: [ [Object] ],
    path: [ 'SaveFacebookUser' ]
  }
}
```

And this log in the app side:
```shell
Array [
  Object {
    "locations": Array [
      Object {
        "column": 3,
        "line": 4,
      },
    ],
    "message": "getaddrinfo EAI_AGAIN us-east-1",
    "stack": "Error: getaddrinfo EAI_AGAIN us-east-1
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)",
  },
]

Error fetching GraphQL query 'ContinueWithFacebookMutation' with variables '{"input":{"token":"EAAKOpJUurDkBAAcLkb0i4jWnypGZAf3wriz53ppxHb4RDInMX9E3E7PEJZBOpQXWdaow2rctQVE34vTESMM8N74y23RTUaZAUPpW11qNVpEytEf4FL9AJLLHkZA5lEjoecR6O8WlRw8JF6hvQqSRt2EpIiBLGhNfZCpymgSzw77lReZCqfAaZCFp2gsrnmHdC8IIIAO574qSx0vWXa2tdd8X8T39UDZA1MqLObrgtK6MRIpxw95hlZChq","expires":5161926,"permissions":["public_profile","email"]}}': [{"message":"getaddrinfo EAI_AGAIN us-east-1","locations":[{"line":4,"column":3}],"stack":"Error: getaddrinfo EAI_AGAIN us-east-1\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}]
```
So when you try to login again, it works fine.

**Comment by mrviniciux** [comment]
I grab this one
